name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  trivy-iac-scan:
    name: IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy IaC scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: "image"
          image-ref: ghcr.io/lopesboa/menubao-marketing:sha-${{ env.SHORT_SHA }}
          # format: 'table'
          format: 'github'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          # scan-ref: "."
          # format: "sarif"
          output: "trivy-iac-results.sarif"
          # severity: "CRITICAL,HIGH"
          # scanners: "misconfig,secret"

      - name: Upload IaC scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-iac-results.sarif"
          category: "IaC"

  trivy-fs-scan:
    name: Filesystem Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-fs-results.sarif"
          severity: "CRITICAL,HIGH"
          scanners: "vuln,secret"
          exit-code: "1"

      - name: Upload filesystem scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-fs-results.sarif"
          category: "Filesystem"
